[connections.snowflake]
account = "AZGTZTJ-HJB64724"
user = "BONNAUD"
password = "!Snowflake2me!"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true